apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: financial-data-pvc
  namespace: kilo-guardian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # k3s default storage class
