#!/bin/bash
# Deploy Kilo AI Microservices to K3s
# Generated by Kompose from docker-compose.yml

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="${1:-default}"

echo "=========================================="
echo "Kilo AI Microservices - K3s Deployment"
echo "=========================================="
echo "Namespace: $NAMESPACE"
echo "Manifests: $SCRIPT_DIR"
echo ""

# Check kubectl connection
if ! kubectl cluster-info &>/dev/null; then
    echo "ERROR: Cannot connect to K3s cluster"
    echo "Make sure K3s is running and kubectl is configured"
    exit 1
fi

echo "[1/4] Creating namespace (if needed)..."
kubectl create namespace "$NAMESPACE" 2>/dev/null || true

echo "[2/4] Applying PersistentVolumeClaims..."
kubectl apply -n "$NAMESPACE" -f "$SCRIPT_DIR"/*-persistentvolumeclaim.yaml

echo "[3/4] Applying Services..."
kubectl apply -n "$NAMESPACE" -f "$SCRIPT_DIR"/*-service.yaml

echo "[4/4] Applying Deployments..."
kubectl apply -n "$NAMESPACE" -f "$SCRIPT_DIR"/*-deployment.yaml

echo ""
echo "=========================================="
echo "Deployment complete!"
echo "=========================================="
echo ""
echo "Check status with:"
echo "  kubectl get pods -n $NAMESPACE"
echo "  kubectl get services -n $NAMESPACE"
echo ""
echo "Watch pods come up:"
echo "  kubectl get pods -n $NAMESPACE -w"
echo ""
echo "Access gateway:"
echo "  kubectl port-forward -n $NAMESPACE svc/gateway 8000:8000"
echo "  curl http://localhost:8000/status"
