apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /home/kilo/Desktop/Kilo_Ai_microservice/k3s-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: library-of-truth
  name: library-of-truth
spec:
  ports:
    - name: "9006"
      port: 9006
      targetPort: 9006
  selector:
    io.kompose.service: library-of-truth
