apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ml-models
  name: ml-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
