apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /home/kilo/Desktop/Kilo_Ai_microservice/k3s-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: reminder
  name: reminder
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: reminder
